FROM maven:3.8.4-openjdk-11-slim AS build

WORKDIR /app

COPY pom.xml ./
COPY src ./src/

RUN mvn package -Dmaven.test.skip

FROM adoptopenjdk:11-jre-hotspot

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]
